language: objective-c
osx_image: xcode9.3beta
xcode_workspace: septa-ios.xcworkspace # path to your xcodeproj folder
xcode_scheme: Pods-septa-iosTests

script:
  xcodebuild test -workspace septa-ios.xcworkspace -scheme Pods-septa-iosTests CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3'



